name = "my-worker"
account_id = "1234567890abcdef1234567890abcdef"
main = "src/index.ts"
compatibility_date = "2024-11-11"
compatibility_flags = ["nodejs_compat"]

route = "https://example.com/*"

[build]
command = "npm run compile"


[[d1_databases]]
binding = "DB"
database_name = "account-bot"
database_id = "00000000-0000-0000-0000-000000000000"

[[r2_buckets]]
binding = "PROOFS"
bucket_name = "payment-proofs"
preview_bucket_name = "payment-proofs-dev"
